spring:
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  messages:
    basename: 
      - messages
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

security:
  jwt:
    secret: ovVBYAe9BR1e6pMD6SM4rZtbFvPzBXCV
    expiresInDays: 2
