spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25000/gys
    username: postgres
    password: postgres

  redis:
    host: localhost
    port: 18000

  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9200
      repositories:
        enabled: true