spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25000/gys
    username: postgres
    password: postgres

  redis:
    host: localhost
    port: 18000

  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9200
      repositories:
        enabled: true

sftp:
  storage:
    host: localhost
    port: 22
    username: burakpadr
    password: xxx
    remoteBasePath: Documents/nginx/gys-storage/
    remoteImagesBasePath: images/
    remoteFilesBasePath: files/

static-server:
  url: http://localhost:9000/