spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25000/gys
    username: postgres
    password: postgres

  redis:
    host: localhost
    port: 18000

  mail:
    host: smtp.gmail.com
    port: 587
    username: b.padir99@gmail.com
    password: fqrjsxdqyshjjrkm
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

app:
  storage:
    # Base properties

    base-url: /storage
    base-path: /Users/burakpadr/Documents/gys-storage
    images-base-path: ${app.storage.base-path}/images
    files-base-path: ${app.storage.base-path}/files

    # Specific paths and their relative urls

    real-estate-images-path: ${app.storage.images-base-path}/real-estates
    real-estate-images-relative-url: ${app.storage.base-url}/images/real-estates

  image:
    width: 500
    height: 333
