spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25000/gys
    username: postgres
    password: postgres
    
  data:
    redis:
      host: localhost
      port: 18000

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

app:
  storage:
    # Base properties

    base-url: /storage
    base-path: ${user.home}/gys-storage
    images-base-path: ${app.storage.base-path}/images
    files-base-path: ${app.storage.base-path}/files

    # Specific paths and their relative urls

    real-estate-images-path: ${app.storage.images-base-path}/real-estates
    real-estate-images-relative-url: ${app.storage.base-url}/images/real-estates

    rental-contract-files-path: ${app.storage.files-base-path}/rental-contracts
    rental-contract-files-relative-url: ${app.storage.base-url}/files/rental-contracts

    payment-declaration-files-path: ${app.storage.files-base-path}/payment-declarations
    payment-declaration-files-relative-url: ${app.storage.base-url}/files/payment-declarations

  image:
    width: 500
    height: 333

integration:
  tcmb:
    protocol: https
    domain-name: www.tcmb.gov.tr
    kurlar-context-path: kurlar
